name: lint

on:
  push:
    branches:
      - '**'

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install asdf
      uses: asdf-vm/actions/setup@v1

    - name: asdf cache
      id: asdf-cache
      uses: actions/cache@v2
      with:
        path: ~/.asdf/
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

    - name: Install CD tools from .tool-versions
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@v1

    - name: Run make lint
      run: |
        make lint
